(require :thinkofher.core.langs.lsp)
(require :thinkofher.core.langs.c)
(require :thinkofher.core.langs.go)
(require :thinkofher.core.langs.web)
(require :thinkofher.core.langs.lisps)
(require :thinkofher.core.langs.data)
