(require :thinkofher.core.packer)
(require :thinkofher.core.basics)
(require :thinkofher.core.settings)
(require :thinkofher.core.langs)
(require :thinkofher.core.keymaps)
(require :thinkofher.core.plugins)
(require :thinkofher.core.theme)
