(require :thinkofher.core.plugins.telescope)
(require :thinkofher.core.plugins.netrw)
(require :thinkofher.core.plugins.signify)
(require :thinkofher.core.plugins.treesitter)
(require :thinkofher.core.plugins.sneak)
(require :thinkofher.core.plugins.mini)
